### ISSUE TITLE
More flexible event listening

### ISSUE THREAD

**Issue by akru** [airalab/hs-web3#38]
> It will be great to create broadcast event filters to receive events from all smart contracts.

One approach is create multi-parameter `Event` typeclass

```haskell
class Event a e where
  eventFilter :: a -> Filter e
```

and instances for common event cases like

```haskell
instance Event () e where ...
-- ^ Broadcast event listener (listen event from all contracts)
instance Event Address e where ...
-- ^ Unicast event listener (listen event from address)
instance Event [Address] e where ...
-- ^ Multiple address event listener
```

and also will be interested event filter conversion instance:

```haskell
instance Event a b => Event (Filter b) e where ...
```

For this case `event` function type can be presented as:
```haskell
event :: forall p i ni a e .
         ( Provider p
         , DecodeEvent i ni e
         , Event a e
         )
      => a
      -> (e -> ReaderT Change (Web3 p) EventAction)
      -> Web3 p ()
```
and usage case like
```haskell
event tokenAddress $ \(Transfer{...}) ->
    liftIO . print $ transferTo

event () $ \(Transfer{...}) ->
    liftIO . print $ transferTo
```

**Comment by akru** [comment]
@blinky3713 What do you think about it?

**Comment by blinky3713** [comment]
I mean, these are certainly described as being valid in the [JSON-RPC docs](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter) so it seems like a good idea to me even if no one is using them now.

Another thing I would like to propose is that we allow a second `event` like function for handling a list of events with a handler rather than a single event. The reason for this is that then you can process these in parallel. For example, often times we are putting certain events in a postgres database, which as of right now means we insert them one by one rather than a bulk insert. 

maybe something like this

```haskell
eventBatch :: c
          => Filter e
          -> ([e] -> ReaderT Change (Web3 p) EventAction)
          -> Web3 p ()
```

**Comment by akru** [comment]
So, in my opinion, latest block event listener can not spawn a lot of events because incoming block have period 10-15 sec.
Another case - read events from block range, e.g. from 10000 to 100000, in this case handlers can be spawned in parallel by event machine, or parallel partial read of block range. It can be interesting for performance of blockchain analyzers.

**Comment by blinky3713** [comment]
yeah the 2nd options is more what i had in mind -- during a database restore, or when spinning up a new instance i would like that machine to catch up as fast as possible, meaning I would specify the "window" `in eventMany'` to be several blocks, and i would like to do bullk inserts, or in the case where the processing order doesnt matter i want to do them in parallel.

**Comment by akru** [comment]
Chosen another approach, Event typeclass is deprecated.
