### ISSUE TITLE
What happened to the live test suites?

### ISSUE THREAD

**Issue by blinky3713** [airalab/hs-web3#58]
I saw a notice in the change logs that mentioned that you are no longer running the live test suites as part of CI? I have reason to believe whatever modifications you have made to this library have broken something with event monitoring. I assume you are still running these tests because they are important, but the normal way we set it up with a truffle deployment then testing the web3:live test suite seems broken. There are no updates in the README that mention how to run them now locally.

Also, I don't see any PR for these most recent changes. Can you link me to one, because it's difficult for me to understand the scope of the changes from individual git commits

**Comment by akru** [comment]
Good day, @blinky3713!

Yes, custom setup was removed in release 0.7, because it was too complicated and makes difficulties for Hackage deploy. But no, live testing is still running in travis ci as you can see in last [builds](https://travis-ci.org/airalab/hs-web3/builds/373663683). I known it's very important.

I replace custom setup by only one `.travis.yaml` string: https://github.com/airalab/hs-web3/blob/master/.travis.yml#L36

Whats about README, yes, testing paragraph can be extended, improved and, in my opinion, moved to separate `.md` documentation file.
