### ISSUE TITLE
web3-0.7.2.0 test suite build failure (from tarball)

### ISSUE THREAD

**Issue by DanBurton** [airalab/hs-web3#63]
It seems that some test suite files are missing from the web3 hackage tarball. This can usually be addressed by list the files under `extra-source-files` in `web3.cabal`

```
/Users/dan/scratch/web3-0.7.2.0/test/Network/Ethereum/Web3/Test/SimpleStorageSpec.hs:1:1: error:
    Exception when trying to run compile-time code:
      test-support/build/contracts/abis/SimpleStorage.json: openFile: does not exist (No such file or directory)
    Code: template-haskell-2.13.0.0:Language.Haskell.TH.Quote.quoteDec
            abiFrom "test-support/build/contracts/abis/SimpleStorage.json"
  |
1 | {-# LANGUAGE DataKinds             #-}
  | ^
```

I was able to reproduce this locally like so:

```bash
stack unpack web3-0.7.2.0 && cd web3-0.7.2.0
echo 'resolver: nightly-2018-05-13' > stack.yaml
stack build --test --bench --no-run-benchmarks
```

**Comment by akru** [comment]
It’s not mistake because this files generated by external tool before testing. Also some kind of testing environment required for ‘live’ tests.

Preparation commands from Travis CI script:
script:

- docker run --rm -d -p 8545:8545 foamspace/cliquebait:latest && sleep 30
- export EXPORT_STORE=.detected-contract-addresses && cd test-support && truffle deploy && ./convertAbi.sh && ./inject-contract-addresses.sh && cd ..

**Comment by DanBurton** [comment]
Ah, ok, thanks for the explanation. The stackage build/test process doesn't support custom prep commands, so we'll leave it marked as an expected "failure."
